# Generated by Django 3.2.3 on 2022-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'boss'), (1, 'teacher'), (2, 'sales'), (3, 'receptionist'), (4, 'parent'), (5, 'potential user')], default=6),
        ),
    ]
