# Generated by Django 3.2.3 on 2022-03-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
    ]
