# Generated by Django 3.2.3 on 2022-03-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_parent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanager',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
    ]
