# Generated by Django 3.2.3 on 2022-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_salesmanager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanager',
            name='total_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
