# Generated by Django 3.2.3 on 2022-03-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('enrolled', models.DateTimeField(auto_now_add=True)),
                ('classes_have', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.parent')),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.salesmanager')),
            ],
        ),
    ]
