# Generated by Django 3.2.3 on 2022-03-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes_have',
            new_name='classes_bought',
        ),
    ]
