# Generated by Django 3.2.3 on 2022-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_classes_have_student_classes_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
