# Generated by Django 3.2.3 on 2022-03-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes_bought',
            new_name='classes_left',
        ),
    ]
