# Generated by Django 3.2.3 on 2022-03-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_parent_address'),
        ('students', '0004_rename_classes_bought_student_classes_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='profiles.parent'),
        ),
    ]
