# Generated by Django 3.2.3 on 2022-03-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_parent_address'),
        ('students', '0005_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sales_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='profiles.salesmanager'),
        ),
    ]
