# Generated by Django 3.2.3 on 2022-03-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_parent_address'),
        ('students', '0006_alter_student_sales_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(related_name='child', to='profiles.Parent'),
        ),
    ]
