# Generated by Django 3.2.3 on 2022-03-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrolled']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
