# Generated by Django 3.2.3 on 2022-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20220313_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
