# Generated by Django 3.2.3 on 2022-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'art'), (2, 'math'), (3, 'casa'), (4, 'chinese'), (5, 'toddlers'), (6, 'music'), (7, 'english'), (8, 'sport'), (5, 'cooking'), (5, 'infants')], default=3)),
            ],
        ),
    ]
