# Generated by Django 3.2.3 on 2022-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0010_auto_20220313_1129'),
        ('profiles', '0011_alter_salesmanager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_period', models.IntegerField(choices=[(0, '9:00-9:45'), (1, '10:00-10:45'), (2, '11:00-11:45'), (3, '14:00-14:45'), (4, '15:00-15:45'), (5, '16:00-16:45'), (6, '17:00-17:45'), (7, '18:00-18:45')], default=0)),
                ('subject', models.IntegerField(choices=[(1, 'art'), (2, 'math'), (3, 'casa'), (4, 'chinese'), (5, 'toddlers'), (6, 'music'), (7, 'english'), (8, 'sport'), (9, 'cooking'), (10, 'infants')], default=0)),
                ('students', models.ManyToManyField(related_name='lessons', to='students.Student')),
                ('teachers', models.ManyToManyField(related_name='lessons', to='profiles.Teacher')),
            ],
        ),
    ]
