# Generated by Django 3.2.3 on 2022-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subjects',
            field=models.IntegerField(choices=[(1, 'art'), (2, 'math'), (3, 'casa'), (4, 'chinese'), (5, 'toddlers'), (6, 'music'), (7, 'english'), (8, 'sport'), (9, 'cooking'), (10, 'infants')], default=1),
        ),
    ]
