# Generated by Django 3.2.3 on 2022-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(),
        ),
    ]
