# Generated by Django 3.2.3 on 2022-03-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20220306_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.salesmanager')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.parent')),
            ],
        ),
    ]
