# Generated by Django 3.2.3 on 2022-03-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_parent_address'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='profiles.salesmanager'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sold_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='profiles.parent'),
        ),
    ]
