# Generated by Django 3.2.3 on 2022-03-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20220310_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['date']},
        ),
    ]
