# Generated by Django 3.2.3 on 2022-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
    ]
