# Generated by Django 3.2.3 on 2022-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
