# Generated by Django 3.2.3 on 2022-03-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sales_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date']},
        ),
    ]
